name: Test with Steampunk Spotter
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Scan Ansible content
        uses: xlab-steampunk/spotter-action@master
        with:
          paths: .
          upload_values: true
          upload_metadata: true
          ansible_version: 2.14
        env:
          SPOTTER_USERNAME: ${{ secrets.SPOTTER_USERNAME }}
          SPOTTER_PASSWORD: ${{ secrets.SPOTTER_PASSWORD }}
