name: Steampunk Spotter
on: push
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@master

      - name: Scan Ansible content
        uses: xlab-steampunk/spotter-action@2.5.0
        with:
          paths: .
          ansible_version: 2.15
          profile: full
        env:
          SPOTTER_API_TOKEN: ${{ secrets.SPOTTER_API_TOKEN }}
