name: Steampunk Spotter
on: push
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install steampunk-spotter
        run: pip install steampunk-spotter

      - name: Run Spotter scan
        run: spotter scan .
        env:
          SPOTTER_API_TOKEN: ${{ secrets.SPOTTER_API_TOKEN }}
