name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible content scan
        uses: xlab-steampunk/spotter-action@3.0.0
        env:
          SPOTTER_TOKEN: ${{ secrets.SPOTTER_API_TOKEN }}
